FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

RUN python manage.py collectstatic --noinput

CMD python manage.py migrate --noinput && gunicorn ecommerce_backend.wsgi:application --bind 0.0.0.0:$PORT
